language: objective-c
osx_image: xcode11.3

before_install:
    - gem install cocoapods -v '1.9.1'
    - pod setup > /dev/null    #/dev/null to prevent long logs
    - gem install xcpretty
    
install:
    - pod install --verbose

podfile: Podfile
xcode_workspace: AviasalesSDKTemplate.xcworkspace
xcode_scheme: AviasalesSDKTemplate
xcode_sdk: 
    - iphonesimulator
    
script:
   - xcodebuild -workspace AviasalesSDKTemplate.xcworkspace -scheme AviasalesSDKTemplate -sdk iphonesimulator build | xcpretty
